FROM python:3.13.3-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV ALLOWED_HOSTS="*"
ENV OPENAI_API_KEY=""
ENV DATABASE_URL=""
ENV LDAP_SERVER="ldap://ldap-server:389"
ENV BASE_DN="dc=example,dc=com"
ENV DOMAIN=""

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]